# -*- coding: utf-8 -*-
"""Test Train Split.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GDw-HK7HbwdslC-Uvc5oLEI8QWWFCZgD
"""

from sklearn.model_selection import train_test_split


X= df['']
#X = features

y=df['']


X_train, X_test, y_train,
y_test = train_test_split(X,y ,random_state=42, train_size=0.8, shuffle=True)